---
- name: Install NVIDIA Docker
  apt:
    name: nvidia-docker2
    state: present
    update_cache: yes

- name: Add NVIDIA Docker repository
  apt_repository:
    repo: 'deb https://nvidia.github.io/nvidia-docker/debian/ $(lsb_release -cs) main'
    state: present

- name: Add NVIDIA Docker GPG key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

