---
- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Clone IrisBench repository
  git:
    repo: 'https://github.com/bryceshirley/iris-gpubench.git'
    dest: '/home/{{ ansible_user }}/iris-gpubench'
    version: master

- name: Install IrisBench
  pip:
    requirements: /home/{{ ansible_user }}/iris-gpubench/requirements.txt
    virtualenv: /home/{{ ansible_user }}/iris-gpubench

